src/app/products/manage-tax-groups/create-tax-group/create-tax-group.component.ts
src/app/products/products-routing.module.ts

fix(CRED-66): added resolver to get tax components

---

src/app/clients/client-stepper/client-general-step/client-general-step.component.html
src/app/clients/client-stepper/client-general-step/client-general-step.component.ts

fix(CRED-64): Incorporation Date Validity extended to 20 years future date

---

src/app/clients/clients-view/general-tab/general-tab.component.html
src/app/clients/clients-view/general-tab/general-tab.component.ts
src/app/products/loan-products/loan-products.component.html
src/assets/translations/en-US.json

fix(CRED-63) Rename columns on client UI

---

src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.html
src/app/products/manage-tax-groups/edit-tax-group/edit-tax-group.component.ts
src/app/products/manage-tax-groups/manage-tax-groups.component.html
src/app/products/manage-tax-groups/manage-tax-groups.component.ts

fix(CRED-73): Fixed Tax Component and Group Creation and List Bugs

---

src/app/clients/clients-view/general-tab/general-tab.component.html

fix(CRED-94): Fixes issues on loan account details section

---

src/app/clients/clients-view/general-tab/general-tab.component.html

fix(CRED-94): Adds a fix to show loan account fields only if applicable

---

src/app/clients/clients-view/general-tab/general-tab.component.html

feat(CRED-21): Update loan status display to include arrears information

---

src/app/clients/client-stepper/client-general-step/client-general-step.component.ts

fix(CRED-98): fixed incorrect incorporation validity date on client preview

---

src/app/clients/clients-view/general-tab/general-tab.component.html

fix(CRED-21): Update loan status display logic to show status only when active

---

src/app/loans/loans-view/charges-tab/charges-tab.component.html
src/app/loans/loans-view/charges-tab/charges-tab.component.scss

(fix:CRED-85):improve alignment of cash values

---

src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.html
src/app/loans/loans-view/repayment-schedule-tab/repayment-schedule-tab.component.scss

fix(CRED-102): Fixes instalment status when rescheduling a loan

---

src/app/clients/clients-view/general-tab/general-tab.component.html
src/assets/translations/en-US.json

feat(CRED-117): Renames Associated Loan ID to Associated Loan Account

---

src/app/loans/loans-view/loan-account-actions/foreclosure/foreclosure.component.ts

fix(CRED-143): Net outstanding amount to get updated based on transaction date

---

src/app/loans/loans-view/charges-tab/charges-tab.component.ts
src/app/loans/loans-view/view-charge/view-charge.component.ts

(fix:CRED-149):waive charge button non functional fix

---

src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.html
src/app/loans/loans-account-stepper/loans-account-charges-step/loans-account-charges-step.component.ts

(fix:111):fixes discrepancy issue

---

src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.html
src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.scss
src/app/loans/loans-view/reschedule-loan-tab/reschedule-loan-tab.component.ts
src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.html
src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.scss
src/app/tasks/checker-inbox-and-tasks-tabs/reschedule-loan/reschedule-loan.component.ts

feat(CRED-103): Enhance reschedule loan tab with additional columns

---

src/app/loans/loans-view/account-details/account-details.component.html

feat[CRED-107] Adds functionality to get loan interest variations

---

src/app/loans/loans-view/general-tab/general-tab.component.html

fix(CR-XXXX): Fixes UI bug on loan account general tab view

---

src/app/organization/holidays/edit-holiday/edit-holiday.component.html
src/app/organization/holidays/edit-holiday/edit-holiday.component.ts

(fix:89):front end adjustments to accomodate edit and deletion

---

src/app/products/loan-products/edit-loan-product/edit-loan-product.component.html

feat(CRED-177) Factor Rate Product Configuration

feat(CRED-177) Factor Rate Product Configuration

---

src/app/loans/loans-view/account-details/account-details.component.html

fix(CRED-107): Fixes Interest rate history 
